### ISSUE TITLE
Cannot use without @types/node and @types/es6-promise

### ISSUE THREAD

**Issue by theteapot** [jakoblorz/postgres-driver#12]
I tried using this node package by installing it and running your example script on my database, however it would fail with the following errors:
`node_modules/pg-promise/typescript/pg-promise.d.ts(414,43): error TS2503: Cannot find namespace 'NodeJS'.`
`node_modules/pg-promise/typescript/pg-subset.d.ts(12,28): error TS2307: Cannot find module 'events'.`
`node_modules/pg-promise/typescript/pg-subset.d.ts(44,34): error TS2304: Cannot find name 'Buffer'.`
`node_modules/postgres-driver/src/database.ts(36,18): error TS2705: An async function or method in ES5/ES3 requiresthe 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.`

I was able to fix these errors by installing the following packages into my test project:
`"@types/es6-promise": "0.0.33"`
`"@types/node": "^8.0.46"`

Perhaps these should be moved from `devDependencies` to `dependencies` in the package.json?

**Comment by jakoblorz** [comment]
Yes you are completely right  :+1:
I just did not try the installation process manually yet and the project I am currently using this module in is installing `"@types/es6-promise": "0.0.33"` and`"@types/node": "^8.0.46"` by itself, so this error did never occured to me!
